"use client";
import { useMemo, useState } from "react";
import { Check, ChevronRight, RotateCcw } from "lucide-react";
import { userMessage } from "@/lib/errors/user-message";
export interface VocabularyRow { vocabulary_id:string; source:string; familiarity:string; seen_count:number; correct_count:number; last_reviewed_at:string|null; next_review_at:string|null; vocabulary_items:{word:string;chinese_meaning:string;part_of_speech:string;simple_example:string|null;example_translation:string|null;common_collocations:string[];toeic_context:string|null} }
type Tab="today"|"mine"|"review"|"familiar";
export function VocabularyDashboard({initialItems,referenceNow}:{initialItems:VocabularyRow[];referenceNow:string}) {
  const [items,setItems]=useState(initialItems),[tab,setTab]=useState<Tab>("today"),[revealed,setRevealed]=useState<string|null>(null),[message,setMessage]=useState(""),[openedAt]=useState(()=>new Date(referenceNow).getTime());
  const shown=useMemo(()=>items.filter((item)=>tab==="mine"||tab==="familiar"&&["familiar","mastered"].includes(item.familiarity)||tab==="review"&&(!item.next_review_at||new Date(item.next_review_at).getTime()<=openedAt)||tab==="today"&&item.familiarity!=="mastered").slice(0,tab==="today"?10:100),[items,tab,openedAt]);
  async function rate(item:VocabularyRow,rating:0|1|2){setMessage("");const response=await fetch("/api/vocabulary/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({vocabularyId:item.vocabulary_id,rating})});const payload=await response.json()as{error?:string;familiarity?:string;nextReviewAt?:string;reviewedAt?:string};if(!response.ok){setMessage(userMessage(payload.error,"無法儲存複習結果。"));return}setItems((all)=>all.map((row)=>row.vocabulary_id===item.vocabulary_id?{...row,familiarity:payload.familiarity??row.familiarity,next_review_at:payload.nextReviewAt??row.next_review_at,last_reviewed_at:payload.reviewedAt??row.last_reviewed_at,seen_count:row.seen_count+1,correct_count:row.correct_count+(rating>0?1:0)}:row));setRevealed(null);setMessage("已安排下次複習。")}
  return <><div className="wrong-filters">{(["today","mine","review","familiar"]as Tab[]).map((value)=><button className={tab===value?"selected":""} onClick={()=>setTab(value)} key={value}>{value==="today"?"今日單字":value==="mine"?"我的單字":value==="review"?"待複習":"已熟悉"}</button>)}</div>{message&&<div className="notice">{message}</div>}<div className="vocabulary-grid">{shown.map((item)=>{const word=item.vocabulary_items,open=revealed===item.vocabulary_id;return <article className="vocabulary-card" key={item.vocabulary_id}><span className="mastery-chip">{familiarityLabel(item.familiarity)}</span><h2>{word.word}</h2>{!open?<button className="button button-small" onClick={()=>setRevealed(item.vocabulary_id)}>顯示中文 <ChevronRight/></button>:<><h3>{word.part_of_speech} · {word.chinese_meaning}</h3>{word.simple_example&&<p><b>例句：</b>{word.simple_example}</p>}{word.example_translation&&<p><b>中文：</b>{word.example_translation}</p>}{word.common_collocations.length>0&&<p><b>常見搭配：</b>{word.common_collocations.join("、")}</p>}{word.toeic_context&&<p><b>TOEIC 情境：</b>{word.toeic_context}</p>}<div className="vocab-rating"><button onClick={()=>rate(item,0)}><RotateCcw/>不熟</button><button onClick={()=>rate(item,1)}>有印象</button><button onClick={()=>rate(item,2)}><Check/>熟悉</button></div></>}</article>})}{!shown.length&&<div className="empty-wrong"><h2>目前沒有符合條件的單字</h2><p>可從錯題的重要單字開始加入。</p></div>}</div></>;
}
function familiarityLabel(value:string){return value==="mastered"?"已掌握":value==="familiar"?"熟悉":value==="improving"?"有印象":"學習中"}
