import{SIMILARITY_CONFIG,recencyTier,thresholdsFor,type SimilarityThresholds}from"@/lib/similarity/similarity-config";
import{buildPartFingerprint,buildPrimaryFingerprint,normalizeText,type SimilarityRecord}from"@/lib/similarity/fingerprint";

export interface SimilarityMetrics{tokenOverlap:number;jaccard:number;bigram:number;trigram:number;levenshtein:number;combinedScore:number}
export interface SimilarityMatch{metrics:SimilarityMetrics;primaryTextScore:number;recentIndex:number|null;matchedPart:number;matchedSkill:string|null;matchedScenario:string|null;threshold:SimilarityThresholds;tier:string;reason:string|null}
export interface SimilarityDecision{rejected:boolean;reason:string|null;match:SimilarityMatch|null}
export interface ComparisonRecord{record:SimilarityRecord;recentIndex:number|null}
const words=(value:string)=>normalizeText(value).split(" ").filter((token)=>token.length>1);
const set=(value:string)=>new Set(words(value));
const intersection=(a:Set<string>,b:Set<string>)=>{let count=0;for(const item of a)if(b.has(item))count+=1;return count;};
export function tokenOverlap(left:string,right:string){const a=set(left),b=set(right);if(!a.size||!b.size)return 0;return intersection(a,b)/Math.min(a.size,b.size);}
export function jaccardSimilarity(left:string,right:string){const a=set(left),b=set(right);if(!a.size||!b.size)return 0;const shared=intersection(a,b);return shared/(a.size+b.size-shared);}
function ngrams(value:string,size:number){const list=words(value);return new Set(list.slice(0,Math.max(0,list.length-size+1)).map((_,index)=>list.slice(index,index+size).join(" ")));}
function dice(a:Set<string>,b:Set<string>){if(!a.size||!b.size)return 0;return 2*intersection(a,b)/(a.size+b.size);}
export function levenshteinRatio(left:string,right:string){const a=normalizeText(left).slice(0,SIMILARITY_CONFIG.levenshteinMaxLength),b=normalizeText(right).slice(0,SIMILARITY_CONFIG.levenshteinMaxLength);if(a===b)return 1;if(!a.length||!b.length)return 0;let previous=Array.from({length:b.length+1},(_,index)=>index);for(let i=1;i<=a.length;i+=1){const current=[i];for(let j=1;j<=b.length;j+=1)current[j]=Math.min(current[j-1]+1,previous[j]+1,previous[j-1]+Number(a[i-1]!==b[j-1]));previous=current;}return 1-previous[b.length]/Math.max(a.length,b.length);}
export function similarityMetrics(left:string,right:string):SimilarityMetrics{const overlap=tokenOverlap(left,right),jaccard=jaccardSimilarity(left,right),bigram=dice(ngrams(left,2),ngrams(right,2)),trigram=dice(ngrams(left,3),ngrams(right,3));const levenshtein=Math.max(jaccard,bigram,trigram)>=SIMILARITY_CONFIG.levenshteinPrefilter?levenshteinRatio(left,right):0;const combinedScore=jaccard*.35+bigram*.25+trigram*.2+levenshtein*.2;return{tokenOverlap:overlap,jaccard,bigram,trigram,levenshtein,combinedScore};}
function rejectionReason(metrics:SimilarityMetrics,primary:SimilarityMetrics,threshold:SimilarityThresholds){if(primary.levenshtein>=threshold.primary||primary.combinedScore>=threshold.primary)return"primary_text";if(metrics.levenshtein>=threshold.levenshtein&&metrics.tokenOverlap>=.82)return"levenshtein";if(metrics.combinedScore>=threshold.combined&&(metrics.jaccard>=threshold.jaccard||metrics.bigram>=threshold.bigram||metrics.trigram>=threshold.trigram))return"combined_score";return null;}
export function evaluateSimilarity(candidate:SimilarityRecord,comparisons:ComparisonRecord[]):SimilarityDecision{let best:SimilarityMatch|null=null;for(const item of comparisons){if(candidate.groupId&&candidate.groupId===item.record.groupId)continue;const samePart1Image=candidate.part===1&&item.record.part===1&&candidate.image?.id===item.record.image?.id;const full=similarityMetrics(samePart1Image?candidate.options.map((option)=>option.text).join(" "):buildPartFingerprint(candidate),samePart1Image?item.record.options.map((option)=>option.text).join(" "):buildPartFingerprint(item.record));const primary=similarityMetrics(buildPrimaryFingerprint(candidate),buildPrimaryFingerprint(item.record));const threshold=thresholdsFor(candidate.part,item.recentIndex,item.recentIndex===null);const reason=rejectionReason(full,primary,threshold);const match={metrics:full,primaryTextScore:Math.max(primary.combinedScore,primary.levenshtein),recentIndex:item.recentIndex,matchedPart:item.record.part,matchedSkill:item.record.grammarPoint??null,matchedScenario:item.record.scenario??null,threshold,tier:recencyTier(item.recentIndex),reason};if(reason)return{rejected:true,reason,match};if(!best||match.metrics.combinedScore>best.metrics.combinedScore)best=match;}return{rejected:false,reason:null,match:best};}
