import{SIMILARITY_CONFIG}from"@/lib/similarity/similarity-config";
import{buildPartFingerprint,buildPrimaryFingerprint,normalizeText,type SimilarityRecord}from"@/lib/similarity/fingerprint";

export interface SimilarityMetrics{tokenOverlap:number;jaccard:number;ngram:number;levenshtein:number;overall:number}
type Thresholds=typeof SIMILARITY_CONFIG.recent|typeof SIMILARITY_CONFIG.batch;
const words=(value:string)=>normalizeText(value).split(" ").filter((token)=>token.length>1);
const set=(value:string)=>new Set(words(value));
const intersection=(a:Set<string>,b:Set<string>)=>{let count=0;for(const item of a)if(b.has(item))count+=1;return count;};
export function tokenOverlap(left:string,right:string){const a=set(left),b=set(right);if(!a.size||!b.size)return 0;return intersection(a,b)/Math.min(a.size,b.size);}
export function jaccardSimilarity(left:string,right:string){const a=set(left),b=set(right);if(!a.size||!b.size)return 0;const shared=intersection(a,b);return shared/(a.size+b.size-shared);}
function ngrams(value:string,size:number){const list=words(value);return new Set(list.slice(0,Math.max(0,list.length-size+1)).map((_,index)=>list.slice(index,index+size).join(" ")));}
function dice(a:Set<string>,b:Set<string>){if(!a.size||!b.size)return 0;return 2*intersection(a,b)/(a.size+b.size);}
export function ngramSimilarity(left:string,right:string){return Math.max(dice(ngrams(left,2),ngrams(right,2)),dice(ngrams(left,3),ngrams(right,3)));}
export function levenshteinRatio(left:string,right:string){const a=normalizeText(left).slice(0,SIMILARITY_CONFIG.levenshteinMaxLength),b=normalizeText(right).slice(0,SIMILARITY_CONFIG.levenshteinMaxLength);if(a===b)return 1;if(!a.length||!b.length)return 0;let previous=Array.from({length:b.length+1},(_,index)=>index);for(let i=1;i<=a.length;i+=1){const current=[i];for(let j=1;j<=b.length;j+=1)current[j]=Math.min(current[j-1]+1,previous[j]+1,previous[j-1]+Number(a[i-1]!==b[j-1]));previous=current;}return 1-previous[b.length]/Math.max(a.length,b.length);}
export function similarityMetrics(left:string,right:string):SimilarityMetrics{const overlap=tokenOverlap(left,right),jaccard=jaccardSimilarity(left,right),ngram=ngramSimilarity(left,right);const levenshtein=Math.max(jaccard,ngram)>=SIMILARITY_CONFIG.levenshteinPrefilter?levenshteinRatio(left,right):0;const overall=Math.max(jaccard*0.45+ngram*0.35+levenshtein*0.2,overlap*0.7+jaccard*0.3);return{tokenOverlap:overlap,jaccard,ngram,levenshtein,overall};}
export function isTooSimilar(candidate:SimilarityRecord,previous:SimilarityRecord[],thresholds:Thresholds){return previous.some((item)=>{if(candidate.groupId&&candidate.groupId===item.groupId)return false;const samePart1Image=candidate.part===1&&item.part===1&&candidate.image?.id===item.image?.id;const fingerprint=samePart1Image?candidate.options.map((option)=>option.text).join(" "):buildPartFingerprint(candidate);const previousFingerprint=samePart1Image?item.options.map((option)=>option.text).join(" "):buildPartFingerprint(item);const metrics=similarityMetrics(fingerprint,previousFingerprint);const primary=buildPrimaryFingerprint(candidate),previousPrimary=buildPrimaryFingerprint(item);const primaryMetrics=primary&&previousPrimary?similarityMetrics(primary,previousPrimary):null;const repeatedPrimary=primary===previousPrimary||(primaryMetrics!==null&&primary.length>=20&&previousPrimary.length>=20&&(primaryMetrics.overall>=.92||primaryMetrics.ngram>=.94||primaryMetrics.levenshtein>=.96));return repeatedPrimary||metrics.overall>=thresholds.overall||metrics.tokenOverlap>=thresholds.tokenOverlap||metrics.jaccard>=thresholds.jaccard||metrics.ngram>=thresholds.ngram||metrics.levenshtein>=thresholds.levenshtein;});}
