import type{QuestionHistoryRow}from"@/lib/toeic/history/question-history";
import{SIMILARITY_CONFIG}from"@/lib/similarity/similarity-config";
import{LISTENING_SKILLS,READING_SKILLS,TOEIC_SCENARIOS}from"@/lib/toeic/rotation/pools";

export interface RotationPlan{preferredScenarios:string[];preferredSkills:string[];avoidScenarios:string[];avoidSkills:string[];avoidTopics:string[];avoidVocabularyDomains:string[];avoidSentencePatterns:string[]}
export function buildRotationPlan(history:QuestionHistoryRow[],part:number,weakSkills:string[]=[]):RotationPlan{const window=history.slice(0,SIMILARITY_CONFIG.rotationWindow);const scenarioCounts=count(window.map((item)=>item.scenario));const skillCounts=count(window.map((item)=>item.grammar_point));const skillPool=part<=4?LISTENING_SKILLS:READING_SKILLS;const preferredScenarios=rankLow(TOEIC_SCENARIOS,scenarioCounts,8);const preferredSkills=rankLow(skillPool,skillCounts,6,weakSkills);return{preferredScenarios,preferredSkills,avoidScenarios:rankHigh(scenarioCounts,6),avoidSkills:rankHigh(skillCounts,6),avoidTopics:rankHigh(count(window.map((item)=>item.topic)),6),avoidVocabularyDomains:rankHigh(count(window.map((item)=>item.vocabulary_domain)),6),avoidSentencePatterns:rankHigh(count(window.map((item)=>item.sentence_pattern)),8)};}
function count(values:Array<string|null>){const result=new Map<string,number>();for(const raw of values){const value=raw?.trim().toLowerCase();if(value)result.set(value,(result.get(value)??0)+1);}return result;}
function rankLow(pool:readonly string[],counts:Map<string,number>,limit:number,boost:string[]=[]){const weak=new Set(boost.map((item)=>item.toLowerCase()));return[...pool].sort((a,b)=>{const aCount=(counts.get(a.toLowerCase())??0)-(weak.has(a.toLowerCase())?0.5:0);const bCount=(counts.get(b.toLowerCase())??0)-(weak.has(b.toLowerCase())?0.5:0);return aCount-bCount||a.localeCompare(b);}).slice(0,limit);}
function rankHigh(counts:Map<string,number>,limit:number){return[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(([value])=>value);}
export function hasMetadataCollision(candidate:{scenario:string;grammarPoint:string;sentencePattern:string},accepted:Array<{scenario:string;grammarPoint:string;sentencePattern:string}>,history:QuestionHistoryRow[]){const normalize=(value:string|null)=>value?.trim().toLowerCase()??"";const key=`${normalize(candidate.scenario)}|${normalize(candidate.grammarPoint)}|${normalize(candidate.sentencePattern)}`;if(accepted.some((item)=>`${normalize(item.scenario)}|${normalize(item.grammarPoint)}|${normalize(item.sentencePattern)}`===key))return true;return history.slice(0,20).filter((item)=>`${normalize(item.scenario)}|${normalize(item.grammar_point)}|${normalize(item.sentence_pattern)}`===key).length>=2;}
