import{NextResponse}from"next/server";
import{generationRequestSchema,type GeneratedQuestion}from"@/lib/ai/schema";
import{AiProviderUnavailableError,getAiProvider}from"@/lib/ai/provider";
import{recommendDifficulty}from"@/lib/toeic/difficulty";
import{rankMasterySkills,type MasteryWeightRow}from"@/lib/toeic/mastery/weighting";
import{vocabularyTargetLimit}from"@/lib/toeic/vocabulary/review";
import{createQuestionHash}from"@/lib/similarity/fingerprint";
import{readingToSimilarityRecord}from"@/lib/similarity/question-records";
import{evaluateSimilarity}from"@/lib/similarity/similarity-service";
import{logSimilarityDiagnostic,regenerationGuidance}from"@/lib/similarity/diagnostics";
import{DUPLICATE_EXHAUSTED_MESSAGE,SIMILARITY_CONFIG}from"@/lib/similarity/similarity-config";
import{createSupabaseServerClient}from"@/lib/supabase/server";
import{saveGeneratedQuestions,toPublicQuestion}from"@/lib/supabase/questions";
import{getQuestionHistory,historyToSimilarityRecord}from"@/lib/toeic/history/question-history";
import{buildRotationPlan}from"@/lib/toeic/rotation/rotation-service";

export async function POST(request:Request){try{
  const input=generationRequestSchema.parse(await request.json());const supabase=await createSupabaseServerClient();if(!supabase)return NextResponse.json({error:"尚未設定 Supabase，請先完成 .env.local。"},{status:503});const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"請先使用 Google 登入，再開始 AI 練習。"},{status:401});
  const[{data:profile},{data:recentAttempts},{data:mastery},history]=await Promise.all([supabase.from("profiles").select("current_estimated_level,target_score").eq("id",user.id).maybeSingle(),supabase.from("attempts").select("is_correct").eq("user_id",user.id).eq("part",input.part).order("answered_at",{ascending:false}).limit(30),supabase.from("skill_mastery").select("skill_id,recent_accuracy,mastery_level,consecutive_correct,consecutive_wrong,last_practiced_at").eq("user_id",user.id),getQuestionHistory(supabase,user.id)]);
  const{data:targetVocabularyRows}=await supabase.from("user_vocabulary").select("vocabulary_items(word)").eq("user_id",user.id).in("familiarity",["learning","improving"]).order("last_reviewed_at",{ascending:true,nullsFirst:true}).limit(vocabularyTargetLimit(input.count));const targetVocabulary=(targetVocabularyRows??[]).flatMap((row)=>{const item=row.vocabulary_items as unknown as{word?:string}|null;return item?.word?[item.word]:[]});
  const partHistory=history.filter((item)=>item.part===input.part),historyRecords=partHistory.map((item,index)=>({record:historyToSimilarityRecord(item),recentIndex:index})),existingHashes=new Set(history.map((item)=>item.question_hash));const recentAccuracy=recentAttempts?.length?recentAttempts.filter((item)=>item.is_correct).length/recentAttempts.length:null;const currentEstimatedLevel=profile?.current_estimated_level??400;const targetScore=input.targetScore??profile?.target_score??550;const rankedMastery=rankMasterySkills((mastery??[])as MasteryWeightRow[],input.part),primaryMastery=rankedMastery[0],weakSkills=rankedMastery.slice(0,5).map((item)=>item.skill_id);const strategy=recommendDifficulty({currentEstimatedLevel,targetScore,recentAccuracy,weakSkillAccuracy:primaryMastery?Number(primaryMastery.recent_accuracy??0)/100:null,masteryLevel:primaryMastery?.mastery_level,consecutiveCorrect:primaryMastery?.consecutive_correct??0,consecutiveWrong:primaryMastery?.consecutive_wrong??0,requested:input.difficulty});const rotation=buildRotationPlan(history,input.part,weakSkills);const provider=getAiProvider();let accepted:Array<GeneratedQuestion&{questionHash:string}>=[],roundsUsed=0,rejectedCount=0,rejectionReasons:string[]=[];
  for(let round=0;round<SIMILARITY_CONFIG.maxGenerationRounds&&accepted.length<input.count;round+=1){roundsUsed=round+1;const grouped=input.part>=6;const count=grouped?input.count:input.count-accepted.length;const generated=await provider.generateQuestions({part:input.part,count,targetScore,currentEstimatedLevel,difficulty:strategy.difficulty,passageMode:input.passageMode,weakSkills:weakSkills.length?weakSkills:strategy.focus,recentScenarios:rotation.avoidScenarios,recentVocabularyDomains:rotation.avoidVocabularyDomains,recentSentencePatterns:rotation.avoidSentencePatterns,rotation,targetVocabulary,regenerateGuidance:regenerationGuidance(rejectionReasons)});const hashed=await Promise.all(generated.map(async(question)=>({question,questionHash:await createQuestionHash(readingToSimilarityRecord(question))})));const{data:historicDuplicates}=await supabase.from("questions").select("question_hash").eq("user_id",user.id).in("question_hash",hashed.map((item)=>item.questionHash));historicDuplicates?.forEach((item)=>existingHashes.add(item.question_hash));const roundAccepted:Array<GeneratedQuestion&{questionHash:string}>=[],nextReasons:string[]=[];
    for(const[itemIndex,item]of hashed.entries()){const record=readingToSimilarityRecord(item.question);const comparison=[...historyRecords,...accepted.map((question)=>({record:readingToSimilarityRecord(question),recentIndex:null})),...roundAccepted.map((question)=>({record:readingToSimilarityRecord(question),recentIndex:null}))];const decision=evaluateSimilarity(record,comparison);const rejectedByHash=existingHashes.has(item.questionHash);const finalReason=rejectedByHash?"hash":decision.reason??"accepted";logSimilarityDiagnostic({part:input.part,attempt:round+1,candidateIndex:itemIndex,hash:item.questionHash,rejectedByHash,decision,finalReason});if(rejectedByHash||decision.rejected){nextReasons.push(finalReason);continue;}roundAccepted.push({...item.question,questionHash:item.questionHash});}
    rejectionReasons=nextReasons;rejectedCount+=hashed.length-roundAccepted.length;if(grouped){if(roundAccepted.length===input.count){accepted=roundAccepted;break;}rejectedCount+=roundAccepted.length;}else for(const item of roundAccepted){if(accepted.length>=input.count)break;existingHashes.add(item.questionHash);accepted.push(item);}
  }
  if(accepted.length!==input.count)return NextResponse.json({error:DUPLICATE_EXHAUSTED_MESSAGE},{status:422});const stored=await saveGeneratedQuestions(supabase,user.id,provider.name,accepted);const{data:session,error:sessionError}=await supabase.from("practice_sessions").insert({user_id:user.id,mode:"self_selected",status:"active",part:input.part,requested_count:stored.length,difficulty:strategy.difficulty,target_score:targetScore,settings:{workingLevel:strategy.workingLevel,strategyReason:strategy.reason,phase4:true,roundsUsed,rejectedCount}}).select("id").single();if(sessionError)throw new Error(`建立練習紀錄失敗：${sessionError.message}`);const{error:linkError}=await supabase.from("practice_session_questions").insert(stored.map((question,index)=>({session_id:session.id,question_id:question.id,position:index+1})));if(linkError)throw new Error(`連結題目失敗：${linkError.message}`);return NextResponse.json({sessionId:session.id,questions:stored.map(toPublicQuestion),strategy,generatedCount:stored.length,generationRounds:roundsUsed,rejectedCount});
}catch(error){if(error instanceof AiProviderUnavailableError)return NextResponse.json({error:error.message},{status:503});return NextResponse.json({error:error instanceof Error?error.message:"目前無法產生新題目，請稍後再試。"},{status:400});}}
