"use client";
import{useEffect,useState}from"react";
import Link from"next/link";
import{ArrowLeft,Check,ChevronRight,CircleAlert,Headphones,LoaderCircle,Pause,Play,RotateCcw,SkipBack,Sparkles,X}from"lucide-react";
import type{Difficulty,QuestionOption,VocabularyEntry}from"@/types/toeic";
import type{TtsSegment}from"@/lib/tts/provider";
import{useTts}from"@/features/listening/use-tts";

interface Speaker{id:string;name:string;voiceRole:string}interface DialogueTurn{speaker:string;text:string}interface ListeningImage{id:string;imageUrl:string;description:string;tags:string[];scene:string;objects:string[];actions:string[];isActive:boolean}
interface PublicListeningQuestion{id:string;part:1|2|3|4;questionType:string;question:string;options:QuestionOption[];difficulty:Difficulty;targetScore:number;topic:string;scenario:string;skill:string;transcript:string;speakers:Speaker[];dialogue:DialogueTurn[];audioGroupId:string|null;audioType:string;image:ListeningImage|null}
interface AnswerResult{isCorrect:boolean;correctAnswer:QuestionOption["id"];explanation:string;translation:string;vocabulary:VocabularyEntry[];grammarPoint:string}type Stage="setup"|"loading"|"quiz"|"finished";
const copy={1:{title:"Photographs",subtitle:"照片描述 · 圖像與動作"},2:{title:"Question–Response",subtitle:"應答問題 · 聽懂問句與間接回答"},3:{title:"Conversations",subtitle:"多人對話 · 問題與下一步"},4:{title:"Talks",subtitle:"短獨白 · 主旨與細節"}}as const;

export function ListeningPractice({part,signedIn}:{part:1|2|3|4;signedIn:boolean}){const[stage,setStage]=useState<Stage>("setup");const[count,setCount]=useState(5);const[difficulty,setDifficulty]=useState<"auto"|Difficulty>("auto");const[questions,setQuestions]=useState<PublicListeningQuestion[]>([]);const[index,setIndex]=useState(0);const[selected,setSelected]=useState<QuestionOption["id"]|null>(null);const[result,setResult]=useState<AnswerResult|null>(null);const[error,setError]=useState("");const[strategy,setStrategy]=useState("");const[correctCount,setCorrectCount]=useState(0);const tts=useTts();const current=questions[index];
  useEffect(()=>{tts.cancel();},[index,tts.cancel]);
  async function generate(){if(!signedIn){setError("請先使用 Google 登入，再開始 Listening 練習。");return;}tts.cancel();setStage("loading");setError("");try{const response=await fetch("/api/listening/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({part,count,...(difficulty==="auto"?{}:{difficulty})})});const payload=await response.json()as{questions?:PublicListeningQuestion[];error?:string;strategy?:{reason:string}};if(!response.ok||!payload.questions?.length)throw new Error(payload.error??"目前無法產生 Listening 題目。");setQuestions(payload.questions);setStrategy(payload.strategy?.reason??"");setIndex(0);setSelected(null);setResult(null);setCorrectCount(0);setStage("quiz");}catch(cause){setError(cause instanceof Error?cause.message:"Listening 題目產生失敗。");setStage("setup");}}
  async function answer(option:QuestionOption["id"]){if(selected||!current)return;tts.cancel();setSelected(option);try{const response=await fetch("/api/attempts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:current.id,selectedAnswer:option})});const payload=await response.json()as AnswerResult&{error?:string};if(!response.ok)throw new Error(payload.error??"無法儲存答案。");setResult(payload);if(payload.isCorrect)setCorrectCount((value)=>value+1);}catch(cause){setSelected(null);setError(cause instanceof Error?cause.message:"無法儲存答案。");}}
  function segments():TtsSegment[]{if(!current)return[];if(part===3)return current.dialogue.map((turn)=>({text:turn.text,speaker:turn.speaker}));if(part===2)return[{text:current.transcript,speaker:"narrator"},...current.options.map((option)=>({text:`${option.id}. ${option.text}`,speaker:"narrator"}))];if(part===1)return current.options.map((option)=>({text:`${option.id}. ${option.text}`,speaker:"narrator"}));return[{text:current.transcript,speaker:current.speakers[0]?.id??"narrator"}];}
  function next(){tts.cancel();if(index+1>=questions.length){setStage("finished");return;}setIndex((value)=>value+1);setSelected(null);setResult(null);setError("");}function reset(){tts.cancel();setStage("setup");setQuestions([]);setIndex(0);setSelected(null);setResult(null);setError("");}
  return <main className="reading-page listening-page"><header className="reading-topbar"><Link href="/practice" aria-label="返回練習選擇"><ArrowLeft/></Link><div><span>LISTENING · PART {part}</span><strong>{copy[part].title}</strong></div>{stage==="quiz"&&<small>{index+1} / {questions.length}</small>}</header>
  {stage==="setup"&&<section className="setup-card"><span className="setup-icon"><Headphones/></span><p className="eyebrow">PART {part}</p><h1>{copy[part].title}</h1><p className="muted">{copy[part].subtitle}</p><div className="setup-fields"><fieldset><legend>題數</legend><div className="segmented">{[5,10].map((value)=><button type="button" className={count===value?"selected":""} onClick={()=>setCount(value)} key={value}>{value} 題</button>)}</div></fieldset><fieldset><legend>難度</legend><div className="segmented four">{(["auto","easy","medium","hard"]as const).map((value)=><button type="button" className={difficulty===value?"selected":""} onClick={()=>setDifficulty(value)} key={value}>{value==="auto"?"系統推薦":value==="easy"?"簡單":value==="medium"?"中等":"困難"}</button>)}</div></fieldset></div><div className="strategy-note"><Sparkles/><span><strong>從 400 分程度循序漸進</strong><small>先練明確關鍵字與常見商務情境，再逐步加入同義改寫和推論。</small></span></div>{!tts.supported&&<ErrorMessage message="此瀏覽器不支援 SpeechSynthesis，請使用最新版 Chrome、Edge 或 Safari。"/>}{error&&<ErrorMessage message={error}/>}<button className="button generate-button" onClick={generate}>AI 生成原創題目 <ChevronRight/></button></section>}
  {stage==="loading"&&<section className="loading-card" aria-live="polite"><LoaderCircle className="spin"/><h1>正在準備 Part {part} Listening…</h1><p>AI 正在建立原創音訊腳本、選項與中文解析。</p></section>}
  {stage==="quiz"&&current&&<section className="question-layout"><div className="question-card"><div className="question-meta"><span>Part {part}</span><span>{current.difficulty}</span><span>{current.audioType}</span></div>{strategy&&index===0&&<div className="mini-strategy"><Sparkles size={16}/>{strategy}</div>}{part===1&&current.image&&<img className="listening-photo" src={current.image.imageUrl} alt={current.image.description}/>}<div className="audio-controls" aria-live="polite"><button className="button" onClick={()=>tts.play(segments())}><Play/> {tts.status==="playing"?"播放中":"播放"}</button><button type="button" onClick={tts.status==="paused"?tts.resume:tts.pause} disabled={tts.status==="idle"} aria-label={tts.status==="paused"?"繼續播放":"暫停"}>{tts.status==="paused"?<Play/>:<Pause/>}</button><button type="button" onClick={()=>tts.play(segments())} aria-label="重新播放"><SkipBack/></button></div>{tts.error&&<ErrorMessage message={tts.error}/>}<h1>{part<=2?"請聽音訊並選出最佳答案。":current.question}</h1><div className="options-list">{current.options.map((option)=>{const correct=result?.correctAnswer===option.id;const wrong=selected===option.id&&result&&!result.isCorrect;return<button key={option.id} disabled={Boolean(selected)} onClick={()=>answer(option.id)} className={`option-card ${correct?"correct":""} ${wrong?"wrong":""}`}><span>{option.id}</span><strong>{part<=2&&!result?`選項 ${option.id}`:option.text}</strong>{correct&&<Check/>}{wrong&&<X/>}</button>})}</div>{error&&<ErrorMessage message={error}/>}</div>{result&&<aside className={`explanation-card ${result.isCorrect?"success":"failure"}`} aria-live="polite"><div className="result-title">{result.isCorrect?<Check/>:<X/>}<span><strong>{result.isCorrect?"答對了！":"再聽一次就會了"}</strong><small>正確答案是 {result.correctAnswer}</small></span></div><Detail title="Transcript"><p className="transcript-text">{current.transcript}</p></Detail><Detail title="中文解析"><p>{result.explanation}</p></Detail><Detail title="應答邏輯／Skill"><p>{result.grammarPoint}</p></Detail><Detail title="重要單字"><div className="vocab-list">{result.vocabulary.map((word)=><div key={`${word.word}-${word.partOfSpeech}`}><strong>{word.word}</strong><span>{word.partOfSpeech} · {word.chineseMeaning}</span></div>)}</div></Detail><Detail title="完整中文翻譯"><p>{result.translation}</p></Detail><button className="button generate-button" onClick={next}>{index+1===questions.length?"查看結果":"下一題"}<ChevronRight/></button></aside>}</section>}
  {stage==="finished"&&<section className="finish-card"><span className="finish-icon"><Check/></span><p className="eyebrow">LISTENING COMPLETE</p><h1>完成 Part {part} 練習！</h1><strong className="result-score">{correctCount} / {questions.length}</strong><div className="finish-actions"><button className="button" onClick={reset}><RotateCcw/>再練一組</button><Link className="button secondary-button" href="/practice">選擇其他 Part</Link></div></section>}</main>}
function ErrorMessage({message}:{message:string}){return<div className="practice-error"><CircleAlert/>{message}</div>}function Detail({title,children}:{title:string;children:React.ReactNode}){return<section className="answer-detail"><h2>{title}</h2>{children}</section>}
