import{NextResponse}from"next/server";
import{listeningGenerationRequestSchema,type GeneratedListeningQuestion}from"@/lib/ai/listening-schema";
import{AiProviderUnavailableError,getAiProvider}from"@/lib/ai/provider";
import{recommendDifficulty}from"@/lib/toeic/difficulty";
import{createQuestionHash}from"@/lib/similarity/fingerprint";
import{listeningToSimilarityRecord}from"@/lib/similarity/question-records";
import{isTooSimilar}from"@/lib/similarity/similarity-service";
import{DUPLICATE_EXHAUSTED_MESSAGE,SIMILARITY_CONFIG}from"@/lib/similarity/similarity-config";
import{createSupabaseServerClient}from"@/lib/supabase/server";
import{saveGeneratedListeningQuestions,toPublicListeningQuestion}from"@/lib/supabase/questions";
import{selectListeningImages}from"@/lib/listening/images";
import{getQuestionHistory,historyToSimilarityRecord}from"@/lib/toeic/history/question-history";
import{buildRotationPlan,hasMetadataCollision}from"@/lib/toeic/rotation/rotation-service";

export async function POST(request:Request){try{
  const input=listeningGenerationRequestSchema.parse(await request.json());const supabase=await createSupabaseServerClient();if(!supabase)return NextResponse.json({error:"尚未設定 Supabase。"},{status:503});const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"請先使用 Google 登入，再開始 Listening 練習。"},{status:401});
  const[{data:profile},{data:recentAttempts},{data:mastery},history]=await Promise.all([supabase.from("profiles").select("current_estimated_level,target_score").eq("id",user.id).maybeSingle(),supabase.from("attempts").select("is_correct").eq("user_id",user.id).eq("part",input.part).order("answered_at",{ascending:false}).limit(30),supabase.from("skill_mastery").select("skill_id,recent_accuracy").eq("user_id",user.id).order("recent_accuracy",{ascending:true}).limit(5),getQuestionHistory(supabase,user.id)]);
  const partHistory=history.filter((item)=>item.part===input.part),historyRecords=partHistory.map(historyToSimilarityRecord),existingHashes=new Set(history.map((item)=>item.question_hash));const recentAccuracy=recentAttempts?.length?recentAttempts.filter((item)=>item.is_correct).length/recentAttempts.length:null;const currentEstimatedLevel=profile?.current_estimated_level??400;const targetScore=profile?.target_score??550;const weakSkills=mastery?.map((item)=>item.skill_id)??[];const strategy=recommendDifficulty({currentEstimatedLevel,targetScore,recentAccuracy,weakSkillAccuracy:mastery?.[0]?.recent_accuracy?Number(mastery[0].recent_accuracy)/100:null,requested:input.difficulty});const rotation=buildRotationPlan(history,input.part,weakSkills);const provider=getAiProvider();const recentImageIds=partHistory.flatMap((item)=>{const image=(item.generation_metadata as{image?:{id?:unknown}}|null)?.image;return typeof image?.id==="string"?[image.id]:[];});const attemptedImageIds:string[]=[];let accepted:Array<GeneratedListeningQuestion&{questionHash:string}>=[],roundsUsed=0,rejectedCount=0;
  for(let round=0;round<SIMILARITY_CONFIG.maxGenerationRounds;round+=1){roundsUsed=round+1;const images=input.part===1?selectListeningImages(input.count,[...attemptedImageIds,...recentImageIds]):undefined;images?.forEach((image)=>attemptedImageIds.push(image.id));const generated=await provider.generateListeningQuestions({part:input.part,count:input.count,targetScore,currentEstimatedLevel,difficulty:strategy.difficulty,weakSkills:weakSkills.length?weakSkills:strategy.focus,recentScenarios:rotation.avoidScenarios,images,rotation});const hashed=await Promise.all(generated.map(async(question)=>({question,questionHash:await createQuestionHash(listeningToSimilarityRecord(question))})));const{data:historicDuplicates}=await supabase.from("questions").select("question_hash").eq("user_id",user.id).in("question_hash",hashed.map((item)=>item.questionHash));historicDuplicates?.forEach((item)=>existingHashes.add(item.question_hash));const roundAccepted:Array<GeneratedListeningQuestion&{questionHash:string}>=[];
    for(const item of hashed){const record=listeningToSimilarityRecord(item.question);const comparison=[...historyRecords,...roundAccepted.map(listeningToSimilarityRecord)];const sameGroup=Boolean(item.question.audioGroupId&&roundAccepted.some((other)=>other.audioGroupId===item.question.audioGroupId));if(existingHashes.has(item.questionHash)||isTooSimilar(record,comparison,roundAccepted.length?SIMILARITY_CONFIG.batch:SIMILARITY_CONFIG.recent)||(!sameGroup&&hasMetadataCollision({scenario:item.question.scenario,grammarPoint:item.question.skill,sentencePattern:item.question.sentencePattern},roundAccepted.map((other)=>({scenario:other.scenario,grammarPoint:other.skill,sentencePattern:other.sentencePattern})),partHistory)))continue;roundAccepted.push({...item.question,questionHash:item.questionHash});}
    rejectedCount+=hashed.length-roundAccepted.length;if(roundAccepted.length===input.count){accepted=roundAccepted;break;}rejectedCount+=roundAccepted.length;
  }
  if(accepted.length!==input.count)return NextResponse.json({error:DUPLICATE_EXHAUSTED_MESSAGE},{status:422});const stored=await saveGeneratedListeningQuestions(supabase,user.id,provider.name,accepted);const{data:session,error:sessionError}=await supabase.from("practice_sessions").insert({user_id:user.id,mode:"self_selected",status:"active",part:input.part,requested_count:stored.length,difficulty:strategy.difficulty,target_score:targetScore,settings:{workingLevel:strategy.workingLevel,strategyReason:strategy.reason,listening:true,phase4:true,roundsUsed,rejectedCount}}).select("id").single();if(sessionError)throw new Error(`建立 Listening 練習紀錄失敗：${sessionError.message}`);const{error:linkError}=await supabase.from("practice_session_questions").insert(stored.map((question,index)=>({session_id:session.id,question_id:question.id,position:index+1})));if(linkError)throw new Error(`連結 Listening 題目失敗：${linkError.message}`);return NextResponse.json({sessionId:session.id,questions:stored.map(toPublicListeningQuestion),strategy,generatedCount:stored.length,generationRounds:roundsUsed,rejectedCount});
}catch(error){if(error instanceof AiProviderUnavailableError)return NextResponse.json({error:error.message},{status:503});return NextResponse.json({error:error instanceof Error?error.message:"Listening 題目產生失敗。"},{status:400});}}
