import {NextResponse}from"next/server";
import{listeningGenerationRequestSchema,type GeneratedListeningQuestion}from"@/lib/ai/listening-schema";
import{AiProviderUnavailableError,getAiProvider}from"@/lib/ai/provider";
import{recommendDifficulty}from"@/lib/toeic/difficulty";
import{createQuestionHash,isQuestionTooSimilar,SIMILARITY_CONFIG}from"@/lib/similarity/question-similarity";
import{createSupabaseServerClient}from"@/lib/supabase/server";
import{getRecentQuestions,saveGeneratedListeningQuestions,toPublicListeningQuestion}from"@/lib/supabase/questions";
import{getListeningImage}from"@/lib/listening/images";

export async function POST(request:Request){try{const input=listeningGenerationRequestSchema.parse(await request.json());const supabase=await createSupabaseServerClient();if(!supabase)return NextResponse.json({error:"尚未設定 Supabase。"},{status:503});const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"請先使用 Google 登入，再開始 Listening 練習。"},{status:401});
  const[{data:profile},{data:recentAttempts},{data:mastery},recentQuestions]=await Promise.all([supabase.from("profiles").select("current_estimated_level,target_score").eq("id",user.id).maybeSingle(),supabase.from("attempts").select("is_correct").eq("user_id",user.id).eq("part",input.part).order("answered_at",{ascending:false}).limit(30),supabase.from("skill_mastery").select("skill_id,recent_accuracy").eq("user_id",user.id).order("recent_accuracy",{ascending:true}).limit(5),getRecentQuestions(supabase,user.id,input.part,SIMILARITY_CONFIG.recentQuestionLimitPhase2)]);
  const recentAccuracy=recentAttempts?.length?recentAttempts.filter((item)=>item.is_correct).length/recentAttempts.length:null;const currentEstimatedLevel=profile?.current_estimated_level??400;const targetScore=profile?.target_score??550;const strategy=recommendDifficulty({currentEstimatedLevel,targetScore,recentAccuracy,weakSkillAccuracy:mastery?.[0]?.recent_accuracy?Number(mastery[0].recent_accuracy)/100:null,requested:input.difficulty});const provider=getAiProvider();const generated=await provider.generateListeningQuestions({part:input.part,count:input.count,targetScore,currentEstimatedLevel,difficulty:strategy.difficulty,weakSkills:mastery?.map((item)=>item.skill_id)??strategy.focus,recentScenarios:recentQuestions.map((question)=>question.scenario),image:input.part===1?getListeningImage(input.imageId):undefined});
  const accepted:Array<GeneratedListeningQuestion&{questionHash:string}>=[];for(const question of generated){const questionHash=await createQuestionHash({question:`${question.transcript} ${question.question}`,options:question.options});const otherGroups=accepted.filter((item)=>!question.audioGroupId||item.audioGroupId!==question.audioGroupId);if(recentQuestions.some((recent)=>recent.question_hash===questionHash)||isQuestionTooSimilar({question:`${question.transcript} ${question.question}`,options:question.options},[...recentQuestions,...otherGroups.map((item)=>({question:`${item.transcript} ${item.question}`,options:item.options}))],SIMILARITY_CONFIG.recentThreshold))continue;accepted.push({...question,questionHash});}
  if(accepted.length!==input.count)return NextResponse.json({error:"Listening 題目與近期內容太相似，請重新生成一組。"},{status:422});const stored=await saveGeneratedListeningQuestions(supabase,user.id,provider.name,accepted);const{data:session,error:sessionError}=await supabase.from("practice_sessions").insert({user_id:user.id,mode:"self_selected",status:"active",part:input.part,requested_count:stored.length,difficulty:strategy.difficulty,target_score:targetScore,settings:{workingLevel:strategy.workingLevel,strategyReason:strategy.reason,listening:true}}).select("id").single();if(sessionError)throw new Error(`建立 Listening 練習紀錄失敗：${sessionError.message}`);const{error:linkError}=await supabase.from("practice_session_questions").insert(stored.map((question,index)=>({session_id:session.id,question_id:question.id,position:index+1})));if(linkError)throw new Error(`連結 Listening 題目失敗：${linkError.message}`);return NextResponse.json({sessionId:session.id,questions:stored.map(toPublicListeningQuestion),strategy,generatedCount:stored.length});
}catch(error){if(error instanceof AiProviderUnavailableError)return NextResponse.json({error:error.message},{status:503});return NextResponse.json({error:error instanceof Error?error.message:"Listening 題目產生失敗。"},{status:400});}}
